### ISSUE TITLE
AUR Package?

### ISSUE THREAD

**Issue by Modelmat** [daed/laverna#13]
I know there is an AUR package linked for the upstream (and is what is in the README), can this fork also be made into the AUR?

**Comment by daed** [comment]
@funilrys is the resident AUR package expert and maintainer.  I'd think he can help with this if anyone can.

I would have been reluctant, but I feel good enough about where I've gotten (even being less feature-complete) that I'm onboard with putting my fork out there, provided that there is a means of marking that it's not the primary release.  I think I still want to wait until the next beta I can get put together before doing that though.  I want to clean up some stuff like the debug panel being left open and stuff like that.  It would be nice to fix RemoteStorage first also, since that's been a feature people are vocal about missing.

I don't know much about Arch, to be honest.  Is there an unstable channel or beta or something like that it can be put into so that the 0.7.51 is still the default?

**Comment by funilrys** [comment]
Hi @daed simply give me a definitive name for the fork and I'll create the AUR package :smile_cat:

**Comment by Modelmat** [comment]
We could do something like `laverna-git` or `daed-laverna-git` (the standard AUR package for the upstream is `laverna`). This would ensure they know it's developement (there are other suffixes that can be used to).

**Comment by funilrys** [comment]
@Modelmat Please report to #5 to understand my statement.

**Comment by Modelmat** [comment]
Ah, I see. Can't we create a name temporarily on AUR and change it later?

**Comment by funilrys** [comment]
Indeed it is possible but the merging procedure in kinda long in my opinion as it really depends on the time the Arch Trusted User have. 
I do think that they do an awesome work and giving them another task in queue when I can avoid it is kinda harmful for me psychological and for them if they come around here to check...

So I do prefer to wait for the final name. 
I'm the maintainer of the `laverna` package, will publish a statement in the installation about the deprecation of `laverna` once we got the new package :+1: :smile_cat:

**Comment by Modelmat** [comment]
Okay then. I suppose we'll just have to wait.
Don't suppose you can create one and include the PKGBUILD inside the files of the fork?

**Comment by funilrys** [comment]
@Modelmat please close and report to https://aur.archlinux.org/packages/encryptic/ && https://github.com/encryptic-team/encryptic
